# Global settings applied to the whole site.
#
# “base” is the directory to change to before starting build. If you set base:
#        that is where we will look for package.json/.nvmrc/etc, not repo root!
# “command” is your build command.
# “publish” is the directory to publish (relative to the root of your repo).

[build]
  publish = "dist"
  [[redirects]]
  from = "/"
  to = "/"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200

[[redirects]]
  from = "/login"
  to = "/sign-up"
  status = 200

[[redirects]]
  from = "/login"
  to = "/messenger"
  status = 200

[[redirects]]
  from = "/sign-up"
  to = "/sign-up"
  status = 200

[[redirects]]
  from = "/sign-up"
  to = "/login"
  status = 200

[[redirects]]
  from = "/sign-up"
  to = "/settings"
  status = 200

[[redirects]]
  from = "/sign-up"
  to = "/messenger"
  status = 200

[[redirects]]
  from = "/messenger"
  to = "/messenger"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/messenger"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/login"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/sign-up"
  status = 200


  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true